.\" Copyright (C) 2002  Ben Kibbey <bjk@arbornet.org>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.
.Dd December 17, 2002
.Os
.Dt CBOARD 6
.
.Sh NAME
.
.Nm cboard
.Nd an ncurses chess engine frontend
.
.Sh SYNOPSIS
.
.Nm cboard
.Op Fl hv
.Op Fl p Ar pgnfile
.
.Sh DESCRIPTION
.
.Nm cboard
is a ncurses frontend to
.Xr gnuchess .
.
.Pp
The following command line options are available:
.
.Bl -tag -width
.It Fl p Ar pgnfile
Load a PGN formatted file.
.It Fl v
Version information.
.It Fl h
Program help text.
.El
.
.Sh "CONFIGURATION FILE"
Empty lines and lines beginning with a '#' are ignored. Other lines are
parameter and value pairs which must be on the same line and separated with
one or more space or TAB characters.
.Pp
.Bl -tag -compact
.It Cm book Ar string
The book method to use where string is one of: 
.Ar off , 
.Ar prefer , 
.Ar worst  ,
.Ar best
or
.Ar random . 
The default is 
.Ar prefer .
.Pp
.It Cm jumpcount Ar integer
When viewing move history, you can jump more than one move to the next or
previous move with the UP and DOWN keys. This sets the number of moves to
jump.
.Pp
.It Cm depth Ar integer
The search depth level of the engine when it's it's turn to move.
.Pp
.It Cm agony Ar integer
Enable agony strings in the status window when a caputre is made by setting
this to
.Ar 1 .
Set to
.Ar 0
to disable all agony.
.Pp
.It Cm historyagony Ar integer
Set to 
.Ar 0
to disable agony strings when browsing move history.
.Pp
.It Cm pgntag Ar name Op Ar value
Custom PGN tags to add to new games. This can also be used to overwrite
default tag values.
.El
.
.Sh COLORS
.Bl -tag -compact
.It Cm board_selected Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm board_cursor Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm board_black Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm board_white Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm board_graphics Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm board_coords Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm status_window Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm status_title Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm status_border Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm status_notify Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm status_engine Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm data_window Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm data_title Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm data_border Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm history_window Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm history_title Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm history_border Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm message_window Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm message_title Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm message_border Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm message_prompt Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm input_window Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm input_title Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm input_border Ar foreground Ar background Op Ar cattr Op Ar attr
.It Cm input_prompt Ar foreground Ar background Op Ar cattr Op Ar attr
.El
.Pp
Color and attributes can be modified from the configuration file. There are up
to four values for each parameter. The first two are the foreground and
background colors which must be one of:
.Ar black ,
.Ar white ,
.Ar blue ,
.Ar green ,
.Ar yellow ,
.Ar cyan ,
.Ar magenta
or
.Ar red .
.Pp
The third and fourth values are optional and set terminal attributes. The
third sets attributes for color terminals and the fourth for non-color
terminals. Multiple attributes may be assigned by separating them with a
comma. Note that not all terminals support all attributes. The following
attributes are recognized:
.Ar bold ,
.Ar reverse ,
.Ar dim ,
.Ar standout ,
.Ar underline ,
.Ar blink ,
.Ar invisible 
and
.Ar none .
.Pp
Some color parameters have a _window extension. This will set the default
color and attibutes for all characters for the given parameter set.
.
.Sh FILES
.Bl -tag -compact -width ~/.cboardrc/agony.data
.It Pa ~/.cboard/config
Configuration file.
.It Pa ~/.cboard/agony.data
A list of agony strings, one per line, which is displayed randomly when a
capature has been made.
.It Pa ~/.cboard/nag.data
Appending to this file is fine for custom NAG types, but lines before 140 are
reserved by the PGN standard.
.It Pa ~/.cboard/fifo
A FIFO read by the chess engine for resuming games.
.El
.
.Sh AUTHORS
.
.An "Ben Kibbey" Aq bjk@arbornet.org
